# -*- mode: ruby -*-
# vi: set ft=ruby :

docker_storage_disk = "storage/docker_storage.vdi"

boxes = [
  { :name => 'wit-origin-cache', ip: '192.168.33.10', ssh_port: 2223, docker_storage_disk: "storage/docker_storage_1.vdi" },
  { :name => 'wit-backend', ip: '192.168.33.11', ssh_port: 2224, docker_storage_disk: "storage/docker_storage_2.vdi" },
]

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

    config.vm.box = "ubuntu/trusty64"
    config.vm.provision "shell", path: "provision/setup.sh"

    # Disable default ssh in order to manually assign to a known value
    # https://github.com/mitchellh/vagrant/issues/3232
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true

    boxes.each do |opts|
      config.vm.define opts[:name] do |boxconfig|
        boxconfig.vm.network    "private_network", ip: opts[:ip]
        boxconfig.vm.network    :forwarded_port, guest: 22, host: opts[:ssh_port]
        boxconfig.vm.provider "virtualbox" do |v|
            v.name = opts[:name]
            v.memory = 2048
            v.cpus = 2
            v.customize ["modifyvm", :id, "--nictype1", "virtio"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
            unless File.exist?(opts[:docker_storage_disk])
                v.customize ["createhd", "--filename", opts[:docker_storage_disk], "--size", 8 * 1024]
            end
            v.customize ["storageattach", :id, "--storagectl", "SATAController", "--port", 1, "--device", 0, "--type", "hdd", "--medium", opts[:docker_storage_disk]]
        end
      end
    end
end
