---  
- name: Docker Login
  become: yes
  docker_login: 
    username: "{{ docker_hub_username }}"
    password: "{{ docker_hub_password }}"
    email: "{{ docker_hub_email }}"

- name: Docker Compose UP
  become: yes
  shell: cd {{ app_path }}/docker && docker-compose up -d --force-recreate
