---
- name: install everything that we need to compile ruby and gems
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - git
    - git-core
    - libc6-dev
    - libcurl4-openssl-dev
    - libmysqlclient-dev
    - libpq-dev
    - libreadline6
    - libreadline6-dev
    - libssl-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - ncurses-dev
    - openssl 
    - zlib1g
    - zlib1g-dev

- include: rbenv.yml tags=rbenv
- include: ruby.yml tags=ruby
