# usage:
# ansible-playbook cp_ssl_crts.yml --extra-var "tld=foo.com" --inventory-file hosts --limit subblockofhosts --ask-become-pass
#
---
- name: Copy SSL certs to remote hosts
  hosts: all
  remote_user: "{{ remote_user }}"
#  sudo: yes

  tasks:
  - name: RSYNC | copying over SSL certs
    file: path=/tmp/{{ tld }} state=directory mode=0755

  - name: RSYNC | copying over SSL certs
    command: rsync -aq backup:/data/IT/SSL_Certificates/{{ tld }}/ /tmp/{{ tld }}/

#  - name: CHOWN | fixing permissions
#    command: P=/etc/ssl/private/{{ tld }}; mv ~/tmp/{{ tld }} $P && chown root $P && chgrp root $P   
#    sudo: yes

#  - name: RSYNC | coping over SSL certs
#    synchronize: mode=pull src=/data/IT/SSL_Certificates/{{ tld }} dest=/etc/ssl/private/{{ tld }} rsync_path="sudo rsync"
#    delegate_to: backup
