---
- name: Deploy Github Repo
  hosts: "{{ host }}"
  remote_user: "{{ remote_user }}"

  tasks:
  - name: Application | Create application dir
    become: yes
    file: path={{ source_path }} state=directory owner={{ app_user }} group={{ app_group }} mode=0775
    
  - name: Application | Git pull the latest code
    git: repo=git@github.com:ScientiaMobile/{{ project }}.git
      dest={{ source_path }}/{{ project }}
      accept_hostkey=yes
      force=yes
      version={{branch}}

  roles:

  - role: docker-run
    when: "{{ docker_run | bool }}"
