---
- hosts: all
  sudo: no
  tasks:
  - name: Application | Git pull the latest code
    git: repo=git@github.com:ScientiaMobile/{{ project }}.git
      dest={{ source_path }}/{{ project }}
      accept_hostkey=yes
      force=yes
      version={{branch}}

  - name: Application | Composer install
    composer: command=install working_dir={{ source_path }}/{{ project }}

  # TODO Verify path, user and permissions
  - name: Application | Create Cache dir
    file: path=/tmp/image_cache state=directory owner={{ app_user }} group={{ app_group }} mode=0777
