---
- hosts: all

  tasks:

  - name: Docker | Data
    docker:
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ source_path }}/{{ project }}:/u/apps/site"

  - name: Docker | Beanstalkd
    docker:
      name: "{{project}}-beanstalkd"
      image: scientiamobile/base.beanstalkd
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"

  - name: Docker | PHP-FPM
    docker:
      name: "{{project}}-php-fpm"
      image: scientiamobile/base.php-fpm
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes:
        - "{{ source_path }}/{{ project }}/docker/resources/supervisor-wit-worker.conf:/etc/supervisor/conf.d/wit-origin-cache-worker.conf"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-beanstalkd:beanstalkd"

  - name: Docker | Nginx
    docker:
      name: "{{project}}-nginx"
      image: scientiamobile/base.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-php-fpm:fcgi"
      ports:
        - "80:80"
