---
- hosts: all

  tasks:
  - name: Docker | Data project
    docker:
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ source_path }}/{{ project }}:/u/apps/site"
        - /tmp/image_cache:/u/image_cache

  - name: Docker | Redis
    docker:
      name: "{{project}}-redis"
      image: redis:3
      state: reloaded

  - name: Docker | php fpm project
    docker:
      name: "{{project}}-php-fpm"
      image: scientiamobile/base.php-fpm
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-redis:redis"
  - name: Docker | Nginx
    docker:
      name: "{{project}}-nginx"
      image: scientiamobile/base.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-php-fpm:fcgi"
      ports:
        - "80:80"
