---
- name: Deploy ImageEngine Demo Tool
  hosts: all
  remote_user: "{{ remote_user }}"
  sudo: no

  tasks:
  - name: Application | Git pull the latest code
    git: repo=git@github.com:ScientiaMobile/{{ project }}.git
      dest={{ source_path }}/{{ project }}
      accept_hostkey=yes
      force=yes
      version={{version}}

  - name: Application | Install node.js requirements
    command: "docker run -it --rm -v {{ app_path }}/server:/imgeng-demo -w /imgeng-demo node:latest npm install --silent"

  - name: Application | Check if project data dir exists
    stat: path=/u/data/imgeng-demo
    register: check_project_data_path

  - name: Application | Create MySQL Storage Directory
    when: check_project_data_path.stat.exists == false
    sudo: yes
    file: path=/u/data/imgeng-demo
      state=directory
      mode=0775
      recurse=yes
