# usage:
# ansible-playbook cp_ssl_crts.yml --extra-var "tld=foo.com" --inventory-file hosts --limit subblockofhosts --ask-become-pass
#
---
- name: Copy SSL certs to remote hosts
  hosts: "{{ host }}"
  remote_user: "{{ remote_user }}"
#  sudo: yes
  vars:
    ssl_path: "/etc/ssl/private/{{ tld }}"

  tasks:
  - name: SSL | create tmp dir for certs
    file: path=/tmp/{{ tld }} state=directory mode=0755

#  - name: RSYNC | copying over SSL certs
#    command: rsync -aq backup:/data/IT/SSL_Certificates/{{ tld }}/ /tmp/{{ tld }}/
  - name: RSYNC | synchronizing SSL certs
    synchronize: mode=pull src=/data/IT/SSL_Certificates/{{ tld }} dest=/tmp/{{ tld }} use_ssh_args=true
    delegate_to: backup

  - name: SSL | Move certs to TLD folder
    command: "mv /tmp/{{ tld }} {{ ssl_path }}"
    become: yes

  - name: SSL | Fix permissions
    command: "chown -Rf root:root {{ ssl_path }}"
    become: yes

