---
- name: HOST | master-conf
  hosts: "{{ host }}"
  remote_user: "{{ remote_user }}"
  become: yes
  vars:
    common: false
    openmanage: false
    docker_install: false
    docker_cleanup: false   
    kernel_update: false
    ipa: false
    zabbix: false
  
  roles:

# common roles
#    - { role: common }
  - role: common 
    when: "{{ common | bool }}"

  - role: docker-install 
    when: "{{ docker_install | bool }}"

  - role: docker-cleanup 
    when: "{{ docker_cleanup | bool }}"

  - role: openmanage
    when: "{{ openmanage | bool }}"

  - role: kernel-update
    when: "{{ kernel_update | bool }}"

#  - role: ipa
#    when: "{{ ipa | bool }}"

  - role: zabbix
    when: "{{ zabbix | bool }}"

  - role: install-composer
    when: "{{ install_composer | bool }}"
