---
- name: HOST | master-conf
  hosts: all
  become: yes
  remote_user: "{{ remote_user }}"
  vars:
    openmanage: false
    docker_install: false
    docker_cleanup: false   
    kernel_update: false
    ipa: false
    zabbix: false
  
  roles:

# common roles
#    - { role: common }

  - role: docker-install 
    when: "{{ docker_install | bool }}"

  - role: docker-cleanup 
    when: "{{ docker_cleanup | bool }}"

  - role: openmanage
    when: "{{ openmanage | bool }}"

  - role: kernel-update
    when: "{{ kernel_update | bool }}"

  - role: ipa
    when: "{{ ipa | bool }}"

  - role: zabbix
    when: "{{ zabbix | bool }}"
