---
- name: Copy SSL certs to remote hosts
  hosts: "{{ host }}"
  remote_user: "{{ remote_user }}"
  vars:
    ssl_path: "/etc/ssl/private/{{ tld }}"

  tasks:
  - name: SSL | ensure SSL path exists
    file: path={{ ssl_path }} state=directory mode=0755
    become: yes

  - name: RSYNC | synchronizing SSL certs
    synchronize: mode=push src=/data/IT/SSL_Certificates/{{ tld }}/ dest={{ ssl_path }}/ use_ssh_args=true
    delegate_to: backup
    become: yes

  - name: SSL | Fix permissions
    command: "chown -Rf root:root {{ ssl_path }}"
    become: yes

