---
- name: ANSISTRANO | S3 | Get object from S3
  s3: bucket={{ ansistrano_s3_bucket }} object={{ ansistrano_s3_object }} dest={{ ansistrano_release_path.stdout }} mode=get region={{ ansistrano_s3_region }}
