---
- name: Docker - Remove exited container 
  shell: docker rm $(docker ps -aq)
  ignore_errors: yes

- name: Docker Images - Remove unused images
  shell: docker rmi $(docker images -aq)
  ignore_errors: yes
