---
zabbix_agent_config_server: zabbix.scientiamobile.local
zabbix_agent_config_server_active: zabbix.scientiamobile.local
zabbix_agent_config_hostname: '{{ inventory_hostname_short }}'
zabbix_agent_config_start_agents: 3
zabbix_agent_config_log_size: 500
zabbix_agent_config_enable_remote_commands: 0
