---
- name: Deploy Zabbix-addons for Varnish stats
  hosts: wit-frontend
  remote_user: "{{ remote_user }}"
  sudo: no

  tasks:
  - name: Application | Git pull the latest code
    git: repo=git@github.com:ScientiaMobile/{{ project }}.git
      dest={{ source_path }}/{{ project }}
      accept_hostkey=yes
      force=yes
      version={{version}}

  - name: Dcoker Build | building zabbix-addons image
    command: /varnish/build.sh working_dir={{ app_path }}

  - name: Docker UP | starting zabbix-addons container
    command: /varnish/start.sh working_dir={{ app_path }}
 
