---
- name: Deploy Zabbix-addons for Varnish stats
  hosts: wit-frontend
  remote_user: "{{ remote_user }}"
  sudo: yes

  tasks:
  - name: Application | Git pull the latest code
    git: repo=git@github.com:ScientiaMobile/{{ project }}.git
      dest={{ source_path }}/{{ project }}
      accept_hostkey=yes
      force=yes
      version={{version}}

  - name: Dcoker Build | building zabbix-addons image
    command: chdir={{ app_path }}/varnish ./build.sh

  - name: Docker UP | starting zabbix-addons container
    command: chdir={{ app_path }}/varnish ./start.sh
 
