---
- name: Deploy Zabbix-addons
  hosts: all
  remote_user: "{{ remote_user }}"

  tasks:
  - name: Application | Git pull the latest code
    git: repo=git@github.com:ScientiaMobile/{{ project }}.git
      dest={{ source_path }}/{{ project }}
      accept_hostkey=yes
      force=yes
      version={{version}}

# to do: remove the build tasks once zabbix-addons repo is in "docker-auto-build"

# Varnish module deploy

  - name: Docker Build | building zabbix-addons varnish module
    when: "'wit-frontend' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/varnish ./build.sh

  - name: Docker UP | starting zabbix-addons varnish container
    when: "'wit-frontend' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/varnish ./start.sh

# Beanstalk module deploy

  - name: Docker Hub | Pull base image 
    when: "'wit-origin-cache' in group_names"
    become: yes
    become_user: root
    docker:
      hostname: "{{ansible_hostname}}-doc-base"
      pull: always
      name: "{{project}}-doc-base"
      image: scientiamobile/base.php
      state: stopped
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"

  - name: Docker Build | building zabbix-addons beanstalkd module
    when: "'wit-origin-cache' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/beanstalkd ./build.sh

  - name: Docker UP | starting zabbix-addons beanstalkd container
    when: "'wit-origin-cache' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/beanstalkd ./start.sh

# Diskstats link

  - name: Zabbix-UserParam | Create userparameter link
    sudo: yes
    file: src=/u/apps/zabbix-addons/userparameters/userparameter_zabbix_addons.conf dest=/etc/zabbix/zabbix_agentd.d/userparameter_zabbix_addons.conf
      state=link
