---
- name: Deploy Zabbix-addons
  hosts: all
  remote_user: "{{ remote_user }}"

  tasks:
  - name: Application | Git pull the latest code
    git: repo=git@github.com:ScientiaMobile/{{ project }}.git
      dest={{ source_path }}/{{ project }}
      accept_hostkey=yes
      force=yes
      version={{version}}

# Note: we pull them all here since we're not logged into Docker Hub when we run the start command

  - name: Docker Hub | Updating Zabbix images
    become: yes
    become_user: root
    docker:
      hostname: "{{ansible_hostname}}-doc-base"
      pull: always
      image: "{{ item }}"
      state: stopped
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
    with_items:
      - scientiamobile/base.phusion
      - scientiamobile/base.php
      - scientiamobile/zabbix-addons.varnish
      - scientiamobile/zabbix-addons.php-fpm
      - scientiamobile/zabbix-addons.beanstalkd

# Varnish module deploy

  - name: Docker UP | starting zabbix-addons varnish container
    when: "'wit-frontend' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/varnish ./start.sh

# Redis module deploy
  - name: Docker UP | starting zabbix-addons redis container
    when: "'wit-origin-cache' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/redis ./start.sh wit-origin-cache-redis-metadata

  - name: Docker UP | starting zabbix-addons redis container
    when: "'wit-backend' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/redis ./start.sh wit-backend-redis

# PHP-FPM module deploy

  - name: Docker UP | starting zabbix-addons php-fpm container
    when: "'wit-backend' in group_names or 'wit-origin-cache' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/php-fpm ./start.sh

# NGINX module deploy

  - name: Docker UP | starting zabbix-addons NGINX container
    become: yes
    become_user: root
    command: chdir={{ app_path }}/nginx ./start.sh

# Beanstalk module deploy

  - name: Docker UP | starting zabbix-addons beanstalkd container
    when: "'wit-origin-cache' in group_names"
    become: yes
    become_user: root
    command: chdir={{ app_path }}/beanstalkd ./start.sh

# establish symlink for zabbix userparam

  - name: Zabbix-UserParam | Create userparameter link
    become: yes
    file: src=/u/apps/zabbix-addons/userparameters/userparameter_zabbix_addons.conf dest=/etc/zabbix/zabbix_agentd.d/userparameter_zabbix_addons.conf
      state=link

  - name: Application | Restarting Zabbix Agent
    become: yes
    service: name=zabbix-agent state=restarted

