---
- name: Download Composer
  shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

- name: Setup
  shell: php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

- name: Install
  shell: php composer-setup.php --install-dir=/usr/bin

- name: Cleanup
  shell: php -r "unlink('composer-setup.php');"
