- name: Update APT package cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe force=yes

- name: Install base packages
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-transport-https
    - apticron
    - build-essential
    - debian-goodies
    - htop
    - iftop
    - iotop
    - sudo
    - vim
    - zip
    - unzip
    - wget
    - curl
    - imagemagick
    - policycoreutils

- name: Set timezone
  action: shell echo {{ system_timezone }} > /etc/timezone

- name: Set localtime to timezone
  file: src=/usr/share/zoneinfo/{{ system_timezone }} dest=/etc/localtime

- name: Reconfigure tzdata
  action: command dpkg-reconfigure -f noninteractive tzdata

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

- name: ensure that insserv can be executed via /sbin/insserv
  stat: path=/sbin/insserv follow=yes
  register: insserv

- name: link /usr/lib/insserv to /sbin/insserv
  file: state=link src=/usr/lib/insserv/insserv dest=/sbin/insserv
  when: insserv.stat.exists == False