---
- hosts: all

  remote_user: "{{ remote_user }}"
  sudo: yes

  vars:
    app_path: "{{ source_path }}/{{ project }}/current"

  tasks:
  # Include encrypted vars
  - include_vars: "wit-vars.yml"

  - name: Docker | Data
    docker:
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ app_path }}:/u/apps/site"
        - /tmp/image_cache:/u/image_cache

  - name: Docker | Redis
    docker:
      name: "{{project}}-redis"
      image: redis:3
      state: reloaded

  - name: Docker | PHP-FPM
    docker:
      hostname: "{{hostname}}"
      name: "{{project}}-php-fpm"
      image: scientiamobile/base.php-fpm
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-redis:redis"
  - name: Docker | Nginx
    docker:
      name: "{{project}}-nginx"
      image: scientiamobile/base.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes: "{{ app_path }}/docker/nginx/site.conf:/etc/nginx/conf.d/site.conf"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-php-fpm:fcgi"
      ports:
        - "80:80"
  # TODO: remove composer from docker images
  - name: Composer | Fix vendor dir permissions
    shell: "chown -Rf {{ app_user }}:{{ app_group }} ./vendor"
    args:
      chdir: "{{ app_path }}"
