---
- hosts: wit-backend

  remote_user: "{{ remote_user }}"
  sudo: yes

  tasks:
  # Include encrypted vars
  #- include_vars: "wit-vars.yml"

  - name: Docker | Data
    docker:
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ app_path }}:/u/apps/site"
        - /u/data/wit-backend/image_cache:/u/image_cache

  - name: Docker | Redis
    docker:
      name: "{{project}}-redis"
      image: redis:3
      state: reloaded

  - name: Docker | PHP-FPM
    docker:
      hostname: "{{ansible_hostname}}"
      name: "{{project}}-php-fpm"
      image: scientiamobile/base.php-fpm
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      volumes:
        - "{{ app_path }}/docker/resources/wit-backend-cron:/etc/cron.d/wit-backend-cron"
      links:
        - "{{project}}-redis:redis"
  - name: Docker | Nginx
    docker:
      name: "{{project}}-nginx"
      image: scientiamobile/base.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes: "{{ app_path }}/docker/nginx/site.conf:/etc/nginx/conf.d/site.conf"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-php-fpm:fcgi"
      ports:
        - "80:80"
