---
- hosts: wit-origin-cache

  remote_user: "{{ remote_user }}"
  sudo: yes

  tasks:
  # Include encrypted vars
  #- include_vars: "wit-vars.yml"

  - name: Docker | Data
    docker:
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ app_path }}:/u/apps/site"
        - /u/file_cache:/tmp/file_cache
        - /u/metadata_cache:/tmp/metadata_cache

  - name: Docker | Beanstalkd
    docker:
      name: "{{project}}-beanstalkd"
      image: scientiamobile/base.beanstalkd
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"

  - name: Docker | Redis
    docker:
      name: "{{project}}-redis"
      image: redis:3

  - name: Docker | PHP-FPM
    docker:
      hostname: "{{ansible_hostname}}"
      name: "{{project}}-php-fpm"
      image: scientiamobile/base.php-fpm
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes:
        - "{{ app_path }}/docker/resources/supervisor-wit-worker.conf:/etc/supervisor/conf.d/wit-origin-cache-worker.conf"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-beanstalkd:beanstalkd"
        - "{{project}}-redis:redis"

  - name: Docker | Nginx
    docker:
      name: "{{project}}-nginx"
      image: scientiamobile/base.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-php-fpm:fcgi"
      ports:
        - "80:80"
