---
- name: Deploy WIT Origin Cache
  hosts: wit-origin-cache
  remote_user: "{{ remote_user }}"
  sudo: no

  vars:
    ansistrano_deploy_via: git

  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }

  tasks:
  - name: Application | Composer install
    composer: command=install working_dir={{ app_path }}

  # TODO Verify path, user and permissions
  - name: Application | Create File Cache dir
    file: path=/u/file_cache state=directory owner={{ app_user }} group={{ app_group }} mode=0777
  - name: Application | Create Metadata Cache dir
    file: path=/u/metadata_cache state=directory owner={{ app_user }} group={{ app_group }} mode=0777
