---
- name: Deploy WIT Backend
  hosts: wit-backend
  remote_user: "{{ remote_user }}"
  sudo: no

  vars:
    ansistrano_deploy_via: git
    
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }

  tasks:
  - name: Application | Composer install
    composer: command=install working_dir={{ app_path }}

  # TODO Verify path, user and permissions
  - name: Application | Create Image Cache dir
    file: path=/tmp/image_cache state=directory owner={{ app_user }} group={{ app_group }} mode=0777
