# wurfl xml distribution automation playbook
# _MT_
# daily  xml: production, mdata-1, micrositehost
# weekly xml: insight-iad
#
#
#
---
- name: WURFL.xml distribution
  hosts: all
  remote_user: "{{ remote_user }}"

  tasks:
  - name: ssh | copying and decompressing DAILY.XML.GZ
    shell: ssh data "cat /u/data/snapshot/snapshot_releases/wurfl/daily.xml.gz" | gzip -d > /tmp/wurfl.xml
    when: inventory_hostname != "insight-iad"

  - name: ssh | copying and decompressing WEEKLY.XML.GZ
    shell: ssh data "cat /u/data/snapshot/snapshot_releases/wurfl/weekly.xml.gz" | gzip -d > /tmp/wurfl.xml
    when: inventory_hostname == "insight-iad"

## mdata-1

  - name: Install | mdata-1 
    shell: install -p -m a+r,u+w /tmp/wurfl.xml /opt/ua_repo/wurfl_daily/wurfl.xml
    sudo: yes
    when: inventory_hostname == "mdata-1"

## insight-iad

  - name: Install | insight ftp folder
    shell: install -p -g insight -o insight -m a+r,u+w /tmp/wurfl.xml /u/ftpinsight/wurfl/wurfl.xml
    sudo: yes
    when: inventory_hostname == "insight-iad"

## microsite-host

  - name: Install | Microsite - data
    shell: install -p -m a+r,u+w /tmp/wurfl.xml /u/data/wurfl/wurfl.xml
    sudo: yes
    when: inventory_hostname == "microsite-host"

  - name: Install | Microsite - Tera-WURFL
    shell: install -p -m a+r,u+w /tmp/wurfl.xml /u/apps/Tera-WURFL/data/wurfl.xml
    sudo: yes
    notify:
      - Reload Microsite Tera-WURFL
    when: inventory_hostname == "microsite-host"

## production

  - name: Install | Prod - twsnap
    shell: install -p -m a+r,u+w /tmp/wurfl.xml /var/www/tera-wurfl.com/web/twsnap/data/wurfl.xml
    sudo: yes
    notify:
      - Reload twsnap Tera-WURFL
    when: inventory_hostname == "production"

  - name: Install | Prod - twprod
    shell: install -p -m a+r,u+w /tmp/wurfl.xml /var/www/tera-wurfl.com/web/twprod/data/wurfl.xml
    sudo: yes
    notify:
      - Reload twprod Tera-WURFL
    when: inventory_hostname == "production"

  handlers:
    - name: Reload Microsite Tera-WURFL
      shell: /usr/bin/php /u/apps/Tera-WURFL/admin/cmd_line_admin.php --update=local > /dev/null 2>&1
      sudo: yes
      
    - name: Reload twsnap Tera-WURFL
      shell: /usr/bin/php /var/www/tera-wurfl.com/web/twsnap/admin/cmd_line_admin.php --update=local > /dev/null 2>&1
      sudo: yes

    - name: Reload twprod Tera-WURFL
      shell: /usr/bin/php /var/www/tera-wurfl.com/web/twprod/admin/cmd_line_admin.php --clearCache --update=local > /dev/null
      sudo: yes
      notify:
        - Reload Tera-WURFL Explorer

    - name: Reload Tera-WURFL Explorer
      shell: /usr/bin/php /var/www/tera-wurfl.com/web/explore/admin/reload_all.php > /dev/null 2>&1
      sudo: yes
