# usage:
# ansible-playbook cp_ssl_crts.yml --extra-var "tld=foo.com" --inventory-file hosts --limit subblockofhosts --ask-become-pass
#
#INSIGHT_DEST= /u/ftpinsight/wurfl/wurfl.xml
---
- name: WURFL.xml distribution
  hosts: all
  remote_user: "{{ remote_user }}"

  tasks:
  - name: rsync | copying WEEKLY.XML.GZ
    command: rsync -aqL data:/u/data/snapshot/snapshot_releases/wurfl/weekly.xml.gz /tmp/weekly.xml.gz
    sudo: no

#  - name: RSYNC | coping over XML
#    synchronize: mode=pull src=/u/data/snapshot/snapshot_releases/wurfl/weekly.xml.gz dest=/tmp/weekly.xml.gz
#    delegate_to: data

  - name: Gunzip | unzip 
    command: gzip -d /tmp/weekly.xml.gz > /tmp/wurfl.xml
#    sudo: yes
#    unarchive: src=/tmp/weekly.xml.gz dest=/tmp copy=no


