# usage:
# ansible-playbook cp_ssl_crts.yml --extra-var "tld=foo.com" --inventory-file hosts --limit subblockofhosts --ask-become-pass
#
#INSIGHT_DEST= /u/ftpinsight/wurfl/wurfl.xml
---
- name: WURFL.xml distribution
  hosts: all
  remote_user: "{{ remote_user }}"

  tasks:
  - name: rsync | copying WEEKLY.XML.GZ
    command: rsync -aqL data:/u/data/snapshot/snapshot_releases/wurfl/weekly.xml.gz /tmp/weekly.xml.gz
    sudo: no

  - name: Gunzip | unzip 
    command: cat /tmp/weekly.xml.gz | /bin/gzip -d > /tmp/wurfl.xml 
    sudo: yes
#    unarchive: src=/tmp/weekly.xml.gz dest=/tmp copy=no

#  - name: SSL | Fix permissions
#    command: "chown -Rf root:root {{ ssl_path }}"
#    sudo: yes

#  - name: RSYNC | coping over SSL certs
#    synchronize: mode=pull src=/data/IT/SSL_Certificates/{{ tld }} dest=/etc/ssl/private/{{ tld }} rsync_path="sudo rsync"
#    delegate_to: backup
