---
- name: install build depends
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - libmysqlclient-dev

- name: Add pidfile parameter
  lineinfile: dest=/etc/mysql/my.cnf insertafter="^socket.+" line="pid-file = /tmp/mysql.pid" create=no

- name: Replace old pidfile line
  replace: dest=/etc/mysql/my.cnf regexp='^pid-file = /var/run/mysqld/mysqld.pid' replace="pid-file = /tmp/mysql.pid"
