---
- hosts: wit-origin-cache

  remote_user: "{{ remote_user }}"
  sudo: yes

  tasks:

  - name: Docker | Data
    docker:
      hostname: "{{ansible_hostname}}-doc-data"
      pull: always
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ app_path }}:/u/apps/site"
        - /u/data/wit-origin-cache:/u/data/wit-origin-cache

  - name: Docker | Beanstalkd
    docker:
      hostname: "{{ansible_hostname}}-doc-beanstalkd"
      pull: always
      name: "{{project}}-beanstalkd"
      image: scientiamobile/base.beanstalkd
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"

  - name: Docker | Redis
    docker:
      hostname: "{{ansible_hostname}}-doc-redis"
      name: "{{project}}-redis"
      image: redis:3

  - name: Docker | Redis Medatada
    docker:
      hostname: "{{ansible_hostname}}-doc-redis-metadata"
      name: "{{project}}-redis-metadata"
      image: redis:3
      volumes_from:
        - "{{project}}-data"
      volumes:
        - /u/data/wit-origin-cache/metadata_cache:/data

  - name: Docker | PHP-FPM
    docker:
      hostname: "{{ansible_hostname}}-doc-php-fpm"
      pull: always
      hostname: "{{ansible_hostname}}"
      name: "{{project}}-php-fpm"
      image: scientiamobile/base.php-fpm
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes:
        - "{{ app_path }}/docker/resources/supervisor-wit-worker.conf:/etc/supervisor/conf.d/wit-origin-cache-worker.conf"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-beanstalkd:beanstalkd"
        - "{{project}}-redis:redis"
        - "{{project}}-redis-metadata:redismetadata"

  - name: Docker | Nginx
    docker:
      hostname: "{{ansible_hostname}}-doc-nginx"
      pull: always
      name: "{{project}}-nginx"
      image: scientiamobile/base.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes: "{{ app_path }}/docker/resources/site.conf:/etc/nginx/conf.d/site.conf"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-php-fpm:fcgi"
      ports:
        - "80:80"
