---
- hosts: wit-frontend

  remote_user: "{{ remote_user }}"
  sudo: yes

  tasks:

  - name: Stat | varnish.bin
    stat: path=/u/cache/varnish.bin
    register: varnish_stat

  - name: RM | varnish.bin
    shell: rm -f  /u/cache/varnish.bin
    when: varnish_stat.stat.exists

  - name: Docker | Data
    docker:
      hostname: "{{ansible_hostname}}-doc-data"
      pull: always
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ app_path }}:/u/apps/site"
        - /etc/ssl:/etc/ssl

  - name: Docker | Varnish
    docker:
      hostname: "{{ansible_hostname}}-doc-varnish"
      pull: always
      name: "{{project}}-varnish"
      image: scientiamobile/wit-frontend.varnish
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      volumes:
        - /run/shm/logs:/var/lib/varnish
        - /u/cache:/u/cache
      ports:
        - "80:80"
      env:
        VARNISH_ENV: production

  - name: Docker | Nginx
    docker:
      hostname: "{{ansible_hostname}}-doc-nginx"
      pull: always
      name: "{{project}}-nginx"
      image: scientiamobile/wit-frontend.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-varnish:varnish"
      ports:
        - "443:443"

  - name: Docker | Logger
    docker:
      hostname: "{{ansible_hostname}}-doc-logger"
      pull: always
      name: "{{project}}-logger"
      image: scientiamobile/wit-frontend.logger
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
        - "{{project}}-varnish"
      env:
        FORWARD_LOGS: logs-iad
