---
- hosts: wit-api

  remote_user: "{{ remote_user }}"
  sudo: yes

  tasks:

  - name: Docker | Data
    docker:
      hostname: "{{ansible_hostname}}-doc-data"
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ app_path }}:/u/apps/site"
        - /u/data/imgeng-api/mongodb:/data/db

  - name: Docker | Beanstalkd
    docker:
      hostname: "{{ansible_hostname}}-doc-beanstalkd"
      pull: always
      name: "{{project}}-beanstalkd"
      image: scientiamobile/base.beanstalkd
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"

  - name: Docker | MongoDB
    docker:
      hostname: "{{ansible_hostname}}-doc-mongo"
      name: "{{project}}-mongo"
      image: mongo:3.0
      state: reloaded
      volumes_from:
        - "{{project}}-data"

  - name: Docker | PHP-FPM
    docker:
      hostname: "{{ansible_hostname}}-doc-php-fpm"
      pull: always
      name: "{{project}}-php-fpm"
      image: scientiamobile/imgeng-api.php-fpm
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
      volumes:
        - "{{ app_path }}/docker/resources/supervisor-imgeng-api-workers.conf:/etc/supervisor/conf.d/imgeng-api-workers.conf"
      links:
        - "{{project}}-beanstalkd:beanstalkd"
        - "{{project}}-mongo:mongo"

  - name: Docker | Nginx
    docker:
      hostname: "{{ansible_hostname}}-doc-nginx"
      pull: always
      name: "{{project}}-nginx"
      image: scientiamobile/base.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes: 
        - "{{ app_path }}/docker/nginx/site.conf:/etc/nginx/conf.d/site.conf"
        - "{{ app_path }}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-php-fpm:fcgi"
      expose:
        - "8000"
      ports:
        - "80:80"
