---
- name: Deploy WIT Origin Cache
  hosts: wit-origin-cache
  remote_user: "{{ remote_user }}"
  sudo: no

  # Remove comments if you want to use ansistrano deployments
  #vars:
  #  ansistrano_deploy_via: git
  #roles:
  #  - { role: carlosbuenosvinos.ansistrano-deploy }

  tasks:
  - name: Application | Git pull the latest code
    git: repo=git@github.com:ScientiaMobile/{{ project }}.git
      dest={{ source_path }}/{{ project }}
      accept_hostkey=yes
      force=yes
      version={{version}}

  - name: Application | Composer install
    composer: command=install working_dir={{ app_path }}

  - name: Application | Create File Cache dir
    sudo: yes
    file: path=/u/data/wit-origin-cache/file_cache
      state=directory
      owner=www-data
      group={{ app_user }}
      mode=0775
      recurse=yes

  - name: Application | Create Metadata Cache dir
    sudo: yes
    file: path=/u/data/wit-origin-cache/metadata_cache
      state=directory
      owner=999
      group={{ app_user }}
      mode=0775
      recurse=yes
