---
- hosts: wit-backend

  remote_user: "{{ remote_user }}"
  sudo: yes

  tasks:

  - name: Docker | Data
    docker:
      hostname: "{{ansible_hostname}}-doc-data"
      name: "{{project}}-data"
      image: ubuntu:14.04
      state: reloaded
      volumes:
        - "{{ app_path }}:/u/apps/site"
        - /u/data/wit-backend/image_cache:/u/image_cache

  - name: Docker | Redis
    docker:
      hostname: "{{ansible_hostname}}-doc-redis"
      name: "{{project}}-redis"
      image: redis:3
      state: reloaded
      volumes:
        - "{{ app_path }}/docker/resources/redis.conf:/etc/redis/redis.conf"
        - /u/data/wit-backend/redis:/data
      command: redis-server /etc/redis/redis.conf

  - name: Docker | Node.js
    docker:
      hostname: "{{ansible_hostname}}-doc-node"
      name: "{{project}}-node"
      image: scientiamobile/wit-backend.node
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"

  - name: Docker | PHP-FPM
    docker:
      hostname: "{{ansible_hostname}}-doc-php-fpm"
      pull: always
      name: "{{project}}-php-fpm"
      image: scientiamobile/wit-backend.php-fpm
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes_from:
        - "{{project}}-data"
        - "{{project}}-node"
      volumes:
        - "{{ app_path }}/docker/resources/wit-backend-cron:/etc/cron.d/wit-backend-cron"
        - "{{ app_path }}/docker/php-fpm/resources/service/imgeng-garbage-collection/:/etc/service/imgeng-garbage-collection"
        - "{{ app_path }}/docker/php-fpm/resources/php-fpm/pool.d/www.conf:/etc/php5/fpm/pool.d/www.conf"
        - "{{ app_path }}/docker/php-fpm/resources/php-fpm/php.ini:/etc/php5/fpm/php.ini"
      links:
        - "{{project}}-redis:redis"

  - name: Docker | Nginx
    docker:
      hostname: "{{ansible_hostname}}-doc-nginx"
      pull: always
      name: "{{project}}-nginx"
      image: scientiamobile/base.nginx
      state: reloaded
      email: "{{ docker_hub_email }}"
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      volumes: 
        - "{{ app_path }}/docker/nginx/site.conf:/etc/nginx/conf.d/site.conf"
        - "{{ app_path }}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      volumes_from:
        - "{{project}}-data"
      links:
        - "{{project}}-php-fpm:fcgi"
      expose:
        - "8000"
      ports:
        - "80:80"
