---
- name: resovlconf
  hosts: all
  remote_user: "{{ remote_user }}"

  tasks:
  - name: System | Single-Request set in Resolvconf
    sudo: yes
    lineinfile: dest=/etc/resolvconf/resolv.conf.d/base line="options single-request"

  - name: System | reload resolvconf.d
    sudo: yes
    command: "resolvconf -u"
