---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Passenger repository setup.
- name: Add Passenger apt key.
  apt_key:
    url: "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xAC40B2F7"
    state: present

- name: Add apt HTTPS capabilities.
  apt: name=apt-transport-https state=present

- name: Add Phusion apt repo.
  apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main'
    state: present
    update_cache: yes

# Nginx and passenger installation.
- name: Install Nginx and Passenger.
  apt: "pkg={{ item }} state=installed"
  with_items:
   - nginx-extras
   - passenger

- name: Ensure default virtual host is enabled.
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  when: nginx_add_default_vhost

# Nginx and passenger configuration.
- name: Copy Nginx configuration into place.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Fix nginx passenger_ruby
  lineinfile: dest=/etc/nginx/nginx.conf regexp="passenger_ruby" line="passenger_ruby /home/{{ deploy_user }}/.rbenv/versions/{{ ruby.version }}/bin/ruby;"
