# Common tasks

- name: Add common packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - wget
    - pcregrep
    - htop
    - iftop
    - pv

- name: Ensure consistent hostname
  script: set_hostname.sh {{ ansible_hostname }} {{ ansible_fqdn }}
  #when: ansible_hostname == ansible_fqdn