---
- name: APT | kernel update
  apt: name={{item}} state=present update_cache=yes 
  with_items:
       - linux-image-generic-lts-xenial
       - linux-headers-generic-lts-xenial
#       - linux-image-extra-virtual
