---
- name: Install and Run Project
  hosts: "{{ host }}"
  remote_user: "{{ remote_user }}"

  tasks:
  - name: Composer Install
    composer: command=install working_dir="{{ app_path }}"
    
  - name: Docker Login
    docker_login: 
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      email: "{{ docker_hub_email }}"

  - name: Docker Compose UP
    shell: cd {{ app_path }}/docker && docker-compose up -d
