---
# Path where the code to deploy is
ansistrano_deploy_from: "{{ playbook_dir }}"

# Path where the code must be deployed to
ansistrano_deploy_to: "/var/www/my-app"

# Folder name for the releases
ansistrano_version_dir: "releases"

# Softlink name for the current release
ansistrano_current_dir: "current"

# Shared paths to symlink to release dir
ansistrano_shared_paths: []

# Number of releases to keep in your hosts, if 0, unlimited releases will be kept
ansistrano_keep_releases: 0

# Deployment strategies variables

# Due to runtime variable evaluation, the ansistrano_deploy_via default is actually
# defined in update-code.yml instead of this file. You can still override it in your
# playbook as needed.
# ansistrano_deploy_via: "rsync"

## GIT pull strategy
ansistrano_git_repo: git@github.com:USERNAME/REPO.git
ansistrano_git_branch: master
ansistrano_git_identity_key_path: ""

## RSYNC push strategy
ansistrano_rsync_extra_params: ""

## S3 get strategy
ansistrano_s3_bucket: s3bucket
ansistrano_s3_object: s3object.tgz
ansistrano_s3_region: eu-west-1
